### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by alecsechechel** [KnuffApp/Knuff-Framework#3]
Hello
Thank for knuff framework.

So I install pod "Knuff" to my app.
And try send push to this app. I copy token and choose my certificate. 
But I have error 400: DeviceTokenNotForTopic
How I can fix this?

**Comment by blommegard** [comment]
My guess is that your token is for another App ID, please make sure that your app is signed and run with the correct provisioning profile.

**Comment by alecsechechel** [comment]
Thanks for answer now I try one more time
