### ISSUE TITLE
Knuff not working at office wifi

### ISSUE THREAD

**Issue by smeador** [KnuffApp/Knuff-Framework#5]
I've setup Knuff and everything seems to be configured properly. I've tried repeatedly to auto-detect devices by connecting to the same wifi at my office, but the Mac app would never show the "devices" tab.

I then got the idea that maybe my office (a large corporation) is blocking certain activity or IPs (this has been an issue before), so I tried again at home. Of course, everything works!

Is there a way to debug Knuff network activity to see what exactly is going wrong? Has this issue come up before? I'd like to try to resolve with my IT department, but having some more information would help.

Thanks,
Sean

**Comment by blommegard** [comment]
I see!

Knuff uses the [MultipeerConnectivity](https://developer.apple.com/reference/multipeerconnectivity) framework. I don't really find any documentation (after a quick google session) on the ports it uses, but I suppose that is the issue on your office network.
If you find anything please share! :)
