### ISSUE TITLE
didRegisterForRemoteNotificationsWithDeviceToken or didFailToRegisterForRemoteNotificationsWithError not being called.

### ISSUE THREAD

**Issue by commando24** [KnuffApp/Knuff-Framework#6]
After installing "knuff-framework" in my application using pod didRegisterForRemoteNotificationsWithDeviceToken or didFailToRegisterForRemoteNotificationsWithError not being called.
I tried to remove "knuff-framework" from pod and its work.

**Comment by blommegard** [comment]
Strange!

Can you reproduce where `didFailToRegisterForRemoteNotificationsWithError` is called without Knuff and not called with?
Knuff should not be touching that method at all.

Are you using the debugger or anything else to track what is happening?

**Comment by commando24** [comment]
i had installed firebase in my application after removing firebase these mehods are being called.i don't know how.I will try to find out why these method are not being called.

**Comment by blommegard** [comment]
It seems that the Firebase library swizzle the affected methods and is not calling the original implementation: http://stackoverflow.com/questions/37667753/ios-firebase-push-notifications-how-to-give-firebase-users-device-token-and-s
